
# This file is used to configure the Supabase CLI.

project_id = "kgtfpuvksmqyaraijoal"

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.get-account-info]
verify_jwt = true

[functions.list-coupons]
verify_jwt = true

