
project_id = "kgtfpuvksmqyaraijoal"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[realtime]
enabled = true

[functions]
[functions.create-checkout-session]
verify_jwt = true

[functions.create-coupon]
verify_jwt = true

[functions.get-prices]
verify_jwt = true

[functions.list-coupons]
verify_jwt = true

[functions.sync-prices]
verify_jwt = true

[functions.get-account-info]
verify_jwt = true
